version: "3.7"

services:
  frontend:
    build: front
    ports:
      - 8510:8510
    networks: 
      dn: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend

  backend:
    build: api
    ports:
      - 8020:8020
    networks: 
      dn: 
        aliases: 
          - backend.docker

networks:
  dn:
    external: false