FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
COPY ./utils /code/utils

EXPOSE 8020 

#uvicorn app.main:app --port 8020 
CMD ["uvicorn", "app.main:app", "--port", "8020"]